using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Caching.Memory;
using Ray.Dtos;
using Ray.Utils.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Ray.Utils.Backload
{
    public class UploadSessionManager
    {
        private readonly IMemoryCache _memoryCache;
        private const int DifferenceInBytesToKnowIfFileUploadIsComplete = 10;
        public UploadSessionManager(IMemoryCache memoryCache)
        {
            _memoryCache = memoryCache;
        }

        /// <summary>
        /// Each session is generated by the filename.
        /// </summary>
        /// <param name="request"></param>
        /// <param name="file"></param>
        /// <returns></returns>
        public SessionChunk GetInitialSessionData(HttpRequest request, IFormFile file)
        {
            SessionChunk session = new SessionChunk();
            session.SessionId = EncryptionProvider.GetHash(file.FileName);

            //Its a chunked upload
            if (request.Headers.Any(x => x.Key == "Content-Range"))
            {
                var contentRangeData = request.Headers.Where(x => x.Key == "Content-Range").FirstOrDefault().Value.ToString();
                session.Total = Convert.ToInt32(contentRangeData.Split('/')[1]);
                var bytesUploaded = contentRangeData.Split('/')[0].Split('-');
                session.UploadedBytes = Convert.ToInt32(bytesUploaded[1]);
                session.IsChunkedUpload = true;
                session.CurrentPartNumber = 1;
                return session;
            }
            else //Its a normal upload (not chunked)
            {
                return new SessionChunk()
                {
                    IsChunkedUpload = false,
                    SessionId = EncryptionProvider.GetHash(file.FileName)
                };
            }
        }
        public SessionChunk CreateOrUpdateUploadSession(SessionChunk chunk)
        {
            var session = (SessionChunk)_memoryCache.Get(chunk.SessionId);
            if (session == null)
            {
                chunk.FileId = Guid.NewGuid().ToString();
                session = _memoryCache.Set(chunk.SessionId, chunk);
            }
            else
            {
                session.UploadedBytes = chunk.UploadedBytes;
                session = _memoryCache.Set(chunk.SessionId, session);
            }

            return session;
        }

        public SessionChunk GetById(string Guid)
        {
            var session = (SessionChunk)_memoryCache.Get(Guid);
            return session;
        }

        public void ClearUploadSession(string Guid)
        {
            _memoryCache.Remove(Guid);
        }

        public bool UploadSessionExists(string guid)
        {
            var session = (SessionChunk)_memoryCache.Get(guid);
            return session != null;
        }

        public bool IsFileReadyToMerge(string Guid)
        {
            var session = (SessionChunk)_memoryCache.Get(Guid);
            if (session == null) return false;

            if ((session.Total - session.UploadedBytes) < DifferenceInBytesToKnowIfFileUploadIsComplete)
                return true;

            return false;
        }
    }
}
