services:
  frontendapi:
    build:
      context: .
      dockerfile: Rino.FrontendApi/Dockerfile
    image: rinocode/api-fe-frontendapi:latest
    pull_policy: never
    container_name: frontendapi
    restart: unless-stopped
    networks:
      - cms-network
    ports:
      - "127.0.0.1:8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: ${SQL_CONNECTION}
      appSettings__mongoDb__connectionString: ${MONGO_CONNECTION}
      appSettings__jwt__issuer: ${JWT_ISSUER:-http://apife.rinocode.com/}
      appSettings__jwt__key: ${JWT_KEY:-VisaCardLabJWT-Auth}

  backendapi:
    build:
      context: .
      dockerfile: Rino.BackendApi/Dockerfile
    image: rinocode/api-fe-backendapi:latest
    pull_policy: never
    container_name: backendapi
    restart: unless-stopped
    depends_on:
      - frontendapi
    networks:
      - cms-network
    ports:
      - "127.0.0.1:8081:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ConnectionStrings__DefaultConnection: ${SQL_CONNECTION}
      appSettings__jwt__issuer: ${JWT_ISSUER:-http://apife.rinocode.com/}
      appSettings__jwt__key: ${JWT_KEY:-VisaCardLabJWT-Auth}

  solr:
    build:
      context: ./solr
      dockerfile: Dockerfile
    image: rinocode/api-fe-solr:latest
    pull_policy: never
    container_name: solr
    restart: unless-stopped
    networks:
      - cms-network
    ports:
      - "127.0.0.1:8983:8983"
    environment:
      - SOLR_HEAP=512m
      - SOLR_HOME=/opt/solr/server/solr

networks:
  cms-network:
    external: true