<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.102.4" />
    <PackageReference Include="LazyCache" Version="2.4.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.11" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rino.Dtos\Rino.Dtos.csproj" />
    <ProjectReference Include="..\Rino.Repositories\Rino.Repositories.csproj" />
    <ProjectReference Include="..\Rino.Utils\Rino.Utils.csproj" />
  </ItemGroup>

</Project>
